### ISSUE TITLE
How to print table

### ISSUE THREAD

**Issue by dedisetiaji** [bailabs/tiny-esc-pos#1]
Hi, I just run your lib. But I have problem when I want to combine align in one row. left align and right align. the right align is stick in left align. any solution?Thanks

**Comment by iRaySpace** [comment]
Hello @dedisetiaj,

Just like any word processors, it is not possible to combine both alignments in one row unless they are in a separate column. Maybe, we can write a function in the future iterations.

Thank you for your suggestions. 

Regards,

Ivan

**Comment by dedisetiaji** [comment]
ok, just found the solution. using math to calculate the length of the words. So can decide the length of space. 

Thanks
